services:
  - type: web
    name: airbnb-dashboard2
    env: python
    buildCommand: |
      pip install -r requirements.txt
    preDeployCommand: playwright install chromium
    startCommand: streamlit run airbnb_app.py

