services:
  - type: web
    name: airbnb-dashboard2
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: streamlit run airbnb_app.py --server.port 10000


